# Generated by Django 5.0.3 on 2024-04-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_productcharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_No', models.CharField(max_length=250, unique=True)),
                ('Application_Date', models.DateField()),
                ('Product_Type', models.CharField(max_length=250)),
                ('Member_No', models.CharField(max_length=250)),
                ('Requested_Amount', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Approved_Amount', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Interest', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Member_Name', models.CharField(max_length=250)),
                ('Approval_Date', models.DateField()),
                ('Installments', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Installment_Period', models.DateField()),
                ('Repayment', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Approved', models.BooleanField()),
                ('Dibursement_Date', models.DateField()),
                ('Mode_of_Disbursement', models.CharField(choices=[('Full Disbursement', 'Full Disbursement'), ('Partial Disbursement', 'Partial Disbursement')], default='Full Disbursement', max_length=250)),
                ('Grace_Period', models.DateField()),
                ('Fully_Disbursed', models.BooleanField()),
                ('Loan_Rejection_Reason', models.CharField(max_length=250)),
                ('Outstanding_Balance', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Outstanding_Interest', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Loan_Principal_Repayment', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Loan_Interest_Repayment', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Defaulter_Loan', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('Defaulted_Amount', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
